config:
  build_jobs: 48
  install_tree: $spack/opt/spack-v16
  locks: false
  install_path_scheme: '{compiler.name}-{compiler.version}/{name}/{hash:7}'
  module_roots:
    lmod: $spack/share/spack-v16/lmod
  template_dirs:
    - $spack/var/spack/repos/ornl-spack/templates
