tap "aide-qc/deploy"
tap "microsoft/git"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Official Amazon AWS command-line interface
brew "awscli"
# Parser generator
brew "bison"
# Core application library for C
brew "glib"
# Object-file caching compiler wrapper
brew "ccache"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Statistics utility to count lines of code
brew "cloc"
# Cross-platform make
brew "cmake"
# Provides SOCKS and HTTPS proxy support to SSH
brew "connect"
# Utility that creates projects from templates
brew "cookiecutter"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Tunnel SSH through HTTP proxies
brew "corkscrew"
# Generate documentation for several programming languages
brew "doxygen"
# Identify or delete duplicate files
brew "fdupes"
# GNU compiler collection
brew "gcc"
# GNU compiler collection
brew "gcc@11"
# Library for encoding and decoding .avif files
brew "libavif"
# GitHub command-line tool
brew "gh"
# Library for JPEG-2000 image manipulation
brew "openjpeg"
# Framework for layout and rendering of i18n text
brew "pango"
# Distributed revision control system
brew "git"
# Git extension for versioning large files
brew "git-lfs"
# Find where a commit was merged in git
brew "git-when-merged"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Library to render SVG files using Cairo
brew "librsvg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Next-gen compiler infrastructure
brew "llvm"
# Tool to analyze #includes in C and C++ source files
brew "include-what-you-use"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Add indentation to LaTeX files
brew "latexindent"
# Lua-based environment modules system to modify PATH variable
brew "lmod"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# GUI for vim, made for macOS
brew "macvim"
# Small build system for use with gyp or CMake
brew "ninja"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Flexible test automation for Python
brew "nox"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Python package management tool
brew "poetry"
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Python version management
brew "pyenv"
# Generate types and converters from JSON, Schema, and GraphQL
brew "quicktype"
# Perl-powered file rename script with many helpful built-ins
brew "rename"
# Language for application scale JavaScript development
brew "typescript"
# Cross-platform Git credential storage for multiple hosting providers
cask "git-credential-manager"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Utility to render Jupyter notebooks
cask "jupyter-notebook-viewer"
# Open-source cross-platform alternative to AirDrop
cask "localsend"
# Full TeX Live distribution with GUI applications
cask "mactex"
# Smart card libraries and utilities
cask "opensc-app"
# Open-source code editor
cask "visual-studio-code"
vscode "albertopdrf.root-file-viewer"
vscode "charliermarsh.ruff"
vscode "eamodio.gitlens"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "gkarlos.vscode-ptx-syntax"
vscode "llvm-vs-code-extensions.lldb-dap"
vscode "llvm-vs-code-extensions.vscode-clangd"
vscode "moshfeu.compare-folders"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpp-devtools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.hexeditor"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "robertosoleti.fcl"
vscode "rreverser.llvm"
vscode "surajbarkale.ninja"
