config:
  build_jobs: 32
  install_tree: $spack/opt/spack
  install_path_scheme: '{compiler.name}-{compiler.version}/{name}/{hash:7}'
  module_roots:
    lmod: $spack/share/spack/lmod
  template_dirs:
    - $spack/var/spack/repos/ornl-spack/templates
  build_stage:
    - /localscratch/tmp/$user-spack
    - $tempdir
