config:
  install_tree:
    root: $spack/opt/spack
    projections:
      all: '{compiler.name}-{compiler.version}/{name}/{hash:7}'
  module_roots:
    lmod: $spack/share/spack/lmod
  template_dirs:
  - $spack/var/spack/repos/ornl-spack/templates
