config:
  install_tree:
    root: /lustre/orion/proj-shared/hep143/opt
    projections:
      all: '{compiler.name}-{compiler.version}/{name}/{version}/{hash:4}'
  build_stage:
    - $tempdir/$user/spack-stage
    - $spack/var/spack/stage
  build_jobs: 24
  deprecated: true
  db_lock_timeout: 120
